import type { FieldConfig, ListFieldConfig } from "../components/HomeContentFieldInputs";

export interface SectionConfig {
  key: string;
  label: string;
  description: string;
  /** Which page this section belongs to, for grouping in the admin UI. */
  page: string;
  fields: FieldConfig[];
  lists?: ListFieldConfig[];
  /** The content currently live on the site (the component's hardcoded fallback),
   * used to pre-fill the edit form until an admin actually saves this section. */
  defaultData: Record<string, any>;
}

export const HOME_CONTENT_SECTIONS: SectionConfig[] = [
  {
    key: "google_review_bar",
    page: "Home",
    label: "Google Review Bar",
    description: "The scrolling review strip below the hero slider.",
    fields: [
      { key: "reviewUrl", label: "Google Review Link", type: "text" },
    ],
    lists: [
      {
        key: "reviews",
        label: "Reviews",
        itemFields: [
          { key: "name", label: "Name", type: "text" },
          { key: "text", label: "Review Text", type: "textarea" },
        ],
      },
    ],
    defaultData: {
      reviewUrl: "https://g.page/r/YOUR_GOOGLE_REVIEW_LINK/review",
      reviews: [
        { name: "Farhan Sheikh", text: "Outstanding quality Batik Prints Women Clothing! The cotton fabric is premium and the prints are absolutely beautiful. Ordered wholesale and every piece was perfect. Will definitely order again!" },
        { name: "Aisha Begum", text: "Best Batik Prints Women Clothing manufacturer in Ujjain. Their 60×60 cotton quality is unmatched. Very professional and timely delivery across India. Highly recommended for wholesale buyers." },
        { name: "Rizwan Ali", text: "Great place to get premium Batik Prints Women Clothing! They have an amazing collection with beautiful patterns. The pricing is very competitive for wholesale. Very happy with the quality and service." },
      ],
    },
  },
  {
    key: "curated_collection_text",
    page: "Home",
    label: "Curated Collection Heading",
    description: "Heading/copy above the category grid in the tan \"Curated Collection\" section.",
    fields: [
      { key: "overline", label: "Overline", type: "text" },
      { key: "heading", label: "Heading", type: "textarea" },
      { key: "highlightWord", label: "Highlight Word (optional, colored)", type: "text" },
      { key: "paragraph", label: "Paragraph", type: "textarea" },
      { key: "ctaLabel", label: "CTA Label", type: "text" },
      { key: "ctaLink", label: "CTA Link", type: "text" },
    ],
    defaultData: {
      overline: "Curated for Excellence",
      heading: "Best-Selling Batik Suit Collections\nfor Every Woman",
      highlightWord: "Batik Suit Collections",
      paragraph: "Discover beautiful batik print designs, quality cotton fabric for kurtis, printed cotton fabrics for kurtis, and elegant suit designs complemented by versatile Shalwar Kameez and Dupatta/Chunni styles. From everyday comfort to occasion-ready dressing, each collection is selected for distinctive prints, wearable silhouettes, and dependable fabric quality.",
      ctaLabel: "Explore Collections",
      ctaLink: "/batik-ethnic-wear-for-women",
    },
  },
  {
    key: "shop_by_category",
    page: "Home",
    label: "Shop By Category",
    description: "The 5-category tile grid (used in two places on the home page).",
    fields: [],
    lists: [
      {
        key: "categories",
        label: "Categories",
        itemFields: [
          { key: "title", label: "Title", type: "text" },
          { key: "sub", label: "Sub Label", type: "text" },
          { key: "img", label: "Image", type: "image" },
          { key: "alt", label: "Image Alt Text", type: "text" },
          { key: "href", label: "Link", type: "text" },
        ],
      },
    ],
    defaultData: {
      categories: [
        { title: "Batik Prints Women Clothing", alt: "cotton cloth", img: "/round-category/Batik Cotton Dress for Women Catagory image.webp", href: "/batik-prints-womens-clothing", sub: "Signature" },
        { title: "Ethnic Wear for Women", alt: "ethnic wear for women", img: "/round-category/Ethnic Wear for Women.webp", href: "/batik-ethnic-wear-for-women", sub: "Everyday" },
        { title: "Batik Cotton Dress for Women", alt: "cotton dress for women", img: "/round-category/Batik Prints Women Clothing catagory image.webp", href: "/batik-cotton-dress-for-women", sub: "Comfort" },
        { title: "New Arrival", alt: "cotton kurtis for women", img: "/round-category/New Arrival catagory image.webp", href: "/new-batik-prints-suits", sub: "Latest Drops" },
        { title: "Wholesale", alt: "dresses for women", img: "/round-category/Wholesale catagory image.webp", href: "/wholesale-batik-women-dresses", sub: "Bulk Pricing" },
      ],
    },
  },
  {
    key: "featured_grid_text",
    page: "Home",
    label: "Featured Grid Heading",
    description: "Heading/copy above the 4 featured products (products themselves stay live).",
    fields: [
      { key: "overline", label: "Overline", type: "text" },
      { key: "heading", label: "Heading", type: "textarea" },
      { key: "highlightWord", label: "Highlight Word (optional, colored)", type: "text" },
      { key: "paragraph", label: "Paragraph", type: "textarea" },
      { key: "badgeLabel", label: "Badge Label", type: "text" },
      { key: "ctaLabel", label: "CTA Label", type: "text" },
      { key: "ctaLink", label: "CTA Link", type: "text" },
    ],
    defaultData: {
      overline: "Fresh Batik Styles",
      heading: "New Arrival Women's Suits &\nBatik Dress Material",
      highlightWord: "New Arrival",
      paragraph: "Discover fresh batik blouse designs, printed styles, designer women's dresses, and quality cotton fabric for kurtis—created for effortless everyday dressing. Explore new prints, seasonal styles, and ready-to-wear collections designed around modern Indian fashion.",
      badgeLabel: "Just Added",
      ctaLabel: "Shop New Arrivals",
      ctaLink: "/new-batik-prints-suits",
    },
  },
  {
    key: "lifestyle_banner",
    page: "Home",
    label: "Lifestyle Banner",
    description: "Single image banner with heading and two paragraphs.",
    fields: [
      { key: "heading", label: "Heading", type: "text" },
      { key: "highlightWord", label: "Highlight Word (optional, colored)", type: "text" },
      { key: "paragraph1", label: "Paragraph 1", type: "textarea" },
      { key: "paragraph2", label: "Paragraph 2", type: "textarea" },
      { key: "ctaLabel", label: "CTA Label", type: "text" },
      { key: "ctaLink", label: "CTA Link", type: "text" },
      { key: "image", label: "Image", type: "image" },
    ],
    defaultData: {
      heading: "Batik Dresses & Suit Sets for Every Woman",
      highlightWord: "Every Woman",
      paragraph1: "Explore a thoughtful mix of batik dresses, batik print dresses, suit sets for women, and batik print kurtis, alongside versatile women's dress designs and casual dresses for women, including flattering plus-size batik styles.",
      paragraph2: "From everyday cotton comfort to occasion-ready silhouettes, find styles designed to feel as good as they look.",
      ctaLabel: "Explore Women's Fashion",
      ctaLink: "/batik-ethnic-wear-for-women",
      image: "/round-category/best dresses for women.webp",
    },
  },
  {
    key: "trending_collections_banner",
    page: "Home",
    label: "Trending Collections Banner",
    description: "The 5-tile promotional banner grid.",
    fields: [
      { key: "overline", label: "Overline", type: "text" },
      { key: "heading", label: "Heading", type: "text" },
      { key: "highlightWord", label: "Highlight Word (optional, colored)", type: "text" },
      { key: "paragraph", label: "Paragraph", type: "textarea" },
      { key: "bottomCtaLabel", label: "Bottom CTA Label", type: "text" },
      { key: "bottomCtaLink", label: "Bottom CTA Link", type: "text" },
    ],
    lists: [
      {
        key: "tiles",
        label: "Banner Tiles",
        itemFields: [
          { key: "title", label: "Title", type: "text" },
          { key: "description", label: "Description", type: "textarea" },
          { key: "badgeLabel", label: "Badge Label", type: "text" },
          { key: "ctaLabel", label: "CTA Label", type: "text" },
          { key: "image", label: "Image", type: "image" },
          { key: "alt", label: "Image Alt Text", type: "text" },
          { key: "href", label: "Link", type: "text" },
        ],
      },
    ],
    defaultData: {
      overline: "Batik Styles Worth Wearing",
      heading: "Trending Batik Suits & Women's Clothing",
      highlightWord: "Women's Clothing",
      paragraph: "Explore trending batik prints, fresh Batik Prints Women Clothing designs, cotton dresses for women, and ready-to-wear collections created for everyday shoppers, boutiques, resellers, and fashion businesses.",
      bottomCtaLabel: "Explore All Collections",
      bottomCtaLink: "/batik-prints-womens-clothing",
      tiles: [
        { href: "/batik-prints-womens-clothing", image: "/a.png", alt: "Cotton Cloth", badgeLabel: "Category", title: "Batik Prints Women Clothing", description: "Distinctive batik prints for everyday Indian style.", ctaLabel: "Explore Collection" },
        { href: "/batik-cotton-dress-for-women", image: "/b.png", alt: "Cotton Dress for Women", badgeLabel: "Category", title: "Cotton Dress for Women", description: "Pure cotton dresses for women with elegant batik prints and breathable comfort.", ctaLabel: "Explore Collection" },
        { href: "/batik-ethnic-wear-for-women", image: "/c.png", alt: "Ethnic Wear for Women", badgeLabel: "Category", title: "Ethnic Wear for Women", description: "Statement-making women suits with timeless batik design character.", ctaLabel: "Explore Collection" },
        { href: "/new-batik-prints-suits", image: "/n.png", alt: "Cotton Kurtis for Women", badgeLabel: "Category", title: "New Arrival", description: "Fresh batik suits and new styles added to the collection.", ctaLabel: "Explore Collection" },
        { href: "/wholesale-batik-women-dresses", image: "/category-Homepage/womenclothing.webp", alt: "Dresses for Women", badgeLabel: "Category", title: "Wholesale", description: "Ready-stock fashion collections for growing businesses.", ctaLabel: "Explore Collection" },
      ],
    },
  },
  {
    key: "trending_products_text",
    page: "Home",
    label: "Trending Products Heading",
    description: "Heading/copy above the trending products carousel (products stay live).",
    fields: [
      { key: "overline", label: "Overline", type: "text" },
      { key: "heading", label: "Heading", type: "text" },
      { key: "highlightWord", label: "Highlight Word (optional, colored)", type: "text" },
      { key: "paragraph", label: "Paragraph", type: "textarea" },
      { key: "badgeLabel", label: "Badge Label (e.g. TREND)", type: "text" },
      { key: "ctaLabel", label: "CTA Label", type: "text" },
      { key: "ctaLink", label: "CTA Link", type: "text" },
    ],
    defaultData: {
      overline: "Best Batik Suit Designs",
      heading: "Best-Selling Batik Suits in Cotton Styles",
      highlightWord: "Cotton Styles",
      paragraph: "Discover best-selling batik suit designs, stylish suit designs for women, cotton dress material, and printed dresses made for everyday wear, festive moments, and effortless Indian styling.",
      badgeLabel: "TREND",
      ctaLabel: "Shop Best Sellers",
      ctaLink: "/batik-ethnic-wear-for-women",
    },
  },
  {
    key: "premium_trust",
    page: "Home",
    label: "Premium Trust Section",
    description: "\"Trusted by 1,000+ Retail Partners\" section.",
    fields: [
      { key: "overline", label: "Overline", type: "text" },
      { key: "heading", label: "Heading", type: "textarea" },
      { key: "highlightWord", label: "Highlight Word (optional, colored)", type: "text" },
      { key: "paragraph", label: "Paragraph", type: "textarea" },
      { key: "image", label: "Image (used when no video is set)", type: "image" },
      { key: "videoUrl", label: "Video (optional, overrides image)", type: "video" },
      { key: "ctaLabel", label: "CTA Label", type: "text" },
      { key: "ctaLink", label: "CTA Link", type: "text" },
    ],
    lists: [
      {
        key: "features",
        label: "Trust Features",
        itemFields: [
          { key: "num", label: "Number/Label", type: "text" },
          { key: "t", label: "Title", type: "text" },
          { key: "d", label: "Description", type: "textarea" },
        ],
      },
    ],
    defaultData: {
      overline: "The Legacy of Quality",
      heading: "Trusted by 1,000+ Retail Partners\nfor Quality Batik Fashion",
      highlightWord: "1,000+ Retail Partners",
      paragraph: "For 15+ years, AQSHA Batik Suits has helped boutiques, wholesalers, and resellers source dependable women's dress material, cotton fabrics, Shalwar Kameez, Dupatta/Chunni, and ready-to-sell fashion collections across India.",
      image: "/round-category/indian dresses for girls.webp",
      videoUrl: "",
      ctaLabel: "Discover Our Story",
      ctaLink: "/about-us",
      features: [
        { num: "01", t: "15+ Years of Heritage", d: "Mastering consistent quality, detailed finishing, and dependable production since 2008." },
        { num: "02", t: "Premium Color Fastness", d: "Carefully finished cotton fabrics designed to retain their print, color, and appeal through everyday wear." },
        { num: "03", t: "Ready Dispatch", d: "Efficient production and trusted logistics help keep your fashion stock moving without unnecessary delays." },
        { num: "04", t: "Direct Manufacturer Margins", d: "Source directly from an Ujjain batik manufacturer and access competitive pricing across batik suits, cotton kurtis, dress material, and wholesale fashion collections." },
      ],
    },
  },
  {
    key: "lookbook",
    page: "Home",
    label: "Lookbook",
    description: "The 4-image lookbook grid.",
    fields: [
      { key: "overline", label: "Overline", type: "text" },
      { key: "heading", label: "Heading", type: "textarea" },
      { key: "highlightWord", label: "Highlight Word (optional, colored)", type: "text" },
      { key: "paragraph", label: "Paragraph", type: "textarea" },
      { key: "ctaLabel", label: "CTA Label", type: "text" },
      { key: "ctaLink", label: "CTA Link", type: "text" },
    ],
    lists: [
      {
        key: "looks",
        label: "Looks (exactly 4 recommended — layout is built for 4)",
        itemFields: [
          { key: "title", label: "Title", type: "text" },
          { key: "img", label: "Image", type: "image" },
          { key: "link", label: "Link", type: "text" },
        ],
      },
    ],
    defaultData: {
      overline: "Style Guide",
      heading: "Find Your Perfect Everyday Look",
      highlightWord: "Everyday Look",
      paragraph: "Explore inspiring women's dress designs, batik dress designs, casual dresses for women, and versatile suit sets for women—styled to help you discover your next effortless look.",
      ctaLabel: "Explore More Styles",
      ctaLink: "/batik-ethnic-wear-for-women",
      looks: [
        { title: "Batik Party Wear Suit for Women", img: "/lookbook_emerald.png", link: "/batik-cotton-dress-for-women" },
        { title: "White Cotton Kurti for Women", img: "/lookbook_white.png", link: "/batik-prints-womens-clothing" },
        { title: "Designer Cotton Dress for Women", img: "/lookbook_designer.png", link: "/new-batik-prints-suits" },
        { title: "Premium Casual Kurti for Women", img: "/lookbook_casual.png", link: "/wholesale-batik-women-dresses" },
      ],
    },
  },
  {
    key: "partnership_banner",
    page: "Home",
    label: "Partnership Banner",
    description: "Single full-width image banner, no text.",
    fields: [
      { key: "image", label: "Image", type: "image" },
    ],
    defaultData: {
      image: "/round-category/plus size clothing.webp",
    },
  },
  {
    key: "shoppable_reels",
    page: "Home",
    label: "Shoppable Reels",
    description: "The video reel gallery.",
    fields: [
      { key: "overline", label: "Overline", type: "text" },
      { key: "heading", label: "Heading", type: "text" },
      { key: "highlightWord", label: "Highlight Word (optional, colored)", type: "text" },
      { key: "paragraph1", label: "Paragraph 1", type: "textarea" },
      { key: "paragraph2", label: "Paragraph 2", type: "textarea" },
      { key: "bottomCtaLabel", label: "Bottom CTA Label", type: "text" },
    ],
    lists: [
      {
        key: "reels",
        label: "Reels",
        itemFields: [
          { key: "title", label: "Title", type: "text" },
          { key: "videoUrl", label: "Video", type: "video" },
          { key: "posterUrl", label: "Poster Image", type: "image" },
          { key: "whatsappMsg", label: "WhatsApp Message", type: "textarea" },
        ],
      },
    ],
    defaultData: {
      overline: "AQSHA Batik in Motion",
      heading: "See Batik Dresses, Kurtis & Women's Suits in Motion",
      highlightWord: "in Motion",
      paragraph1: "See the drape, flow, print, and finish behind our latest batik dresses, batik print kurtis, and suit sets for women.",
      paragraph2: "Real fabric. Real movement. Real style.",
      bottomCtaLabel: "Watch the Collection",
      reels: [
        { title: "Festive Collection '26", videoUrl: "/videos/Video-86985.mp4", posterUrl: "/pink_batik_model.png", whatsappMsg: "Hi, I saw the Festive Collection reel and want to know the pricing." },
        { title: "Premium Cotton Batiks", videoUrl: "/videos/Video-22912.mp4", posterUrl: "/cat_batik_cloth.webp", whatsappMsg: "Hi, I am interested in the Cotton Batiks from the reel." },
        { title: "Wholesale Exclusives", videoUrl: "/videos/Video-37755.mp4", posterUrl: "/cat_wholesale.webp", whatsappMsg: "Hi, I want more details on the Wholesale Exclusives reel." },
        { title: "New Arrivals Try-On", videoUrl: "/videos/Video-4836.mp4", posterUrl: "/cat_new_arrival.webp", whatsappMsg: "Hi, I would like to order from the New Arrivals reel." },
        { title: "Artisan Picks", videoUrl: "/videos/Video-5816.mp4", posterUrl: "/pink_batik_model.png", whatsappMsg: "Hi, I would like to order from the Artisan Picks reel." },
        { title: "Trending Styles", videoUrl: "/videos/Video-727.mp4", posterUrl: "/cat_batik_cloth.webp", whatsappMsg: "Hi, I would like to order from the Trending Styles reel." },
      ],
    },
  },
  {
    key: "faq",
    page: "Home",
    label: "FAQ",
    description: "Home page FAQ accordion.",
    fields: [],
    lists: [
      {
        key: "items",
        label: "Questions",
        itemFields: [
          { key: "q", label: "Question", type: "text" },
          { key: "a", label: "Answer", type: "textarea" },
        ],
      },
    ],
    defaultData: {
      items: [
        { q: "Which Batik Cotton Dress for Women is best for daily suits for women?", a: "Cotton 60x60 is a popular choice for daily batik suits because it offers a lightweight, breathable feel suited to regular wear. It works well for batik print kurtis, everyday suits, and comfortable women's clothing." },
        { q: "Can Batik Cotton Dress for Women be used for plus-size women's clothing?", a: "Yes. Batik Cotton Dress for Women can be used to create comfortable plus-size women's clothing with flattering prints and practical silhouettes. Batik print suits, kurtis, and dresses can be designed in different cuts and sizes for comfortable everyday styling." },
        { q: "Why are batik suits becoming popular for women?", a: "Batik suits combine distinctive prints, traditional craftsmanship, and wearable modern silhouettes. From batik print kurtis to complete batik suit sets, they offer a balance of cultural character, comfort, and contemporary fashion." },
        { q: "Are batik print kurtis suitable for everyday wear?", a: "Yes. A well-made batik print kurti can be an excellent everyday option, particularly when crafted from breathable cotton fabric. Cotton-based batik kurtis provide comfortable styling for daily routines while adding distinctive prints to a woman's wardrobe." },
        { q: "Is Ujjain batik good for cotton kurtis for women?", a: "Ujjain has a strong heritage of batik craftsmanship, making its batik styles an appealing choice for cotton kurtis for women. The quality of a particular garment ultimately depends on its cotton fabric, print finishing, construction, and overall comfort." },
      ],
    },
  },
  {
    key: "lead_generation_form",
    page: "Home",
    label: "Lead Generation Form",
    description: "\"Get Personalized Pricing & Catalog\" form section.",
    fields: [
      { key: "title", label: "Title", type: "textarea" },
      { key: "highlightWord", label: "Highlight Word (optional, colored)", type: "text" },
      { key: "description", label: "Description", type: "textarea" },
    ],
    lists: [
      {
        key: "benefits",
        label: "Benefit Bullets",
        itemFields: [
          { key: "text", label: "Benefit", type: "text" },
        ],
      },
    ],
    defaultData: {
      title: "Get Personalized Batik Fabric\nPricing & Catalog",
      highlightWord: "Batik Fabric",
      description: "Explore our latest batik designs, batik print fabric, batik dress material, and batik suit collections with personalized wholesale pricing, ready-stock updates, and collection catalogs from AQSHA Batik Suits.",
      benefits: [
        { text: "Latest Batik Print Design Catalog" },
        { text: "Wholesale Pricing & Bulk Order Support" },
        { text: "Batik & Cotton Dress Material Options" },
        { text: "Printed Cotton Fabric for Kurtis" },
        { text: "Fast WhatsApp Assistance" },
        { text: "Ready-Stock & New Collection Updates" },
      ],
    },
  },
  {
    key: "sticky_enquiry_button",
    page: "Home",
    label: "Sticky Enquiry Button",
    description: "The floating quote button.",
    fields: [
      { key: "label", label: "Button Label", type: "text" },
    ],
    defaultData: {
      label: "Get Quote Now",
    },
  },
  {
    key: "how_to_order",
    page: "Home",
    label: "How To Order",
    description: "The \"How to Order\" step-by-step section (steps themselves stay fixed — only this heading/CTA is editable here).",
    fields: [
      { key: "tag", label: "Tag", type: "text" },
      { key: "title", label: "Title", type: "text" },
      { key: "subtitle", label: "Subtitle", type: "textarea" },
      { key: "ctaText", label: "CTA Label", type: "text" },
    ],
    defaultData: {
      tag: "Wholesale Process",
      title: "How to Order Batik Suits & Women Clothing Online",
      subtitle: "Shop women's clothing online with ease—from exploring batik suit collections and fabrics to selecting your styles, requesting a quote, and receiving your order across India.",
      ctaText: "Start Your Order on WhatsApp",
    },
  },
  {
    key: "target_audience",
    page: "Home",
    label: "Target Audience",
    description: "\"Built for Boutique Owners / Resellers / Wholesalers / Marketplaces\" section.",
    fields: [
      { key: "overline", label: "Overline", type: "text" },
      { key: "heading", label: "Heading", type: "textarea" },
      { key: "highlightWord", label: "Highlight Word (optional, colored)", type: "text" },
      { key: "paragraph", label: "Paragraph", type: "textarea" },
    ],
    lists: [
      {
        key: "audiences",
        label: "Audience Cards",
        itemFields: [
          { key: "t", label: "Title", type: "text" },
          { key: "d", label: "Description", type: "textarea" },
          { key: "b", label: "CTA Badge Text", type: "text" },
        ],
      },
    ],
    defaultData: {
      overline: "Built for Every Buyer",
      heading: "Women's Fashion Collections\nMade for Growing Businesses",
      highlightWord: "Growing Businesses",
      paragraph: "Choose ready-to-sell women's fashion collections, from batik suits and batik blouse designs to women dress material, Shalwar Kameez, and Dupatta/Chunni styles—made for businesses that need dependable fashion stock.",
      audiences: [
        { t: "Boutique Owners", d: "Curated batik suits, blouse designs, and fresh women's clothing collections that help boutiques keep their shelves relevant and their customers coming back.", b: "Fast-Moving Designs" },
        { t: "Resellers", d: "Access attractive suit designs for women, cotton dress material, and ready-to-sell collections designed to support competitive pricing and healthier margins.", b: "Better Margins" },
        { t: "Wholesalers", d: "Source Batik Cotton Dress for Women, printed cotton fabric for kurtis, and scalable women's dress material for consistent bulk fashion orders.", b: "Bulk Consistency" },
        { t: "Marketplaces", d: "Bring searchable women's dresses, batik print styles, and everyday cotton fashion to online customers with collections aligned with modern buying demand.", b: "Trending Stock" },
      ],
    },
  },
  {
    key: "our_story",
    page: "Home",
    label: "Our Story",
    description: "The company history / stats / timeline section.",
    fields: [
      { key: "overline", label: "Overline", type: "text" },
      { key: "heading", label: "Heading", type: "textarea" },
      { key: "highlightWord", label: "Highlight Word (optional, colored)", type: "text" },
      { key: "image", label: "Image", type: "image" },
    ],
    lists: [
      {
        key: "stats",
        label: "Stats",
        itemFields: [
          { key: "v", label: "Value", type: "text" },
          { key: "l", label: "Label", type: "text" },
        ],
      },
      {
        key: "timeline",
        label: "Timeline",
        itemFields: [
          { key: "heading", label: "Heading", type: "text" },
          { key: "paragraph", label: "Paragraph", type: "textarea" },
        ],
      },
    ],
    defaultData: {
      overline: "Our Story",
      heading: "From 15 Handmade Batik Suits to a Trusted Ujjain Batik Manufacturer",
      highlightWord: "Ujjain Batik Manufacturer",
      image: "/round-category/beautiful dresses for women.webp",
      stats: [
        { v: "15+", l: "Years Active" },
        { v: "1,000+", l: "Retail Partners" },
        { v: "1,500+", l: "Monthly Output" },
        { v: "Pan-India", l: "Distribution" },
      ],
      timeline: [
        { heading: "2008 — The First Step", paragraph: "AQSHA Batik Suits began in Bherugarh, Ujjain, with just 15 handmade suits for women. Those early pieces shaped our commitment to quality cotton fabric, careful finishing, and fashion that earns customer trust." },
        { heading: "Building Trust", paragraph: "As demand grew, we built lasting relationships with wholesalers, boutiques, and resellers, supplying women's fashion collections designed around changing market preferences." },
        { heading: "Today — Pan-India Supply", paragraph: "Today, AQSHA Batik Suits supplies fashion retailers and business buyers across Delhi, Punjab, Gujarat, and other Indian markets with dependable batik and cotton fashion collections." },
      ],
    },
  },
  {
    key: "buyer_testimonial_gallery",
    page: "Home",
    label: "Buyer Testimonial Gallery",
    description: "\"What Buyers Say\" WhatsApp screenshot gallery.",
    fields: [
      { key: "heading", label: "Heading", type: "text" },
      { key: "highlightWord", label: "Highlight Word (optional, colored)", type: "text" },
      { key: "statValue1", label: "Stat 1 Value (e.g. 4.9/5)", type: "text" },
      { key: "statLabel1", label: "Stat 1 Label (e.g. Average Rating)", type: "text" },
      { key: "statValue2", label: "Stat 2 Value (e.g. 10K+)", type: "text" },
      { key: "statLabel2", label: "Stat 2 Label (e.g. Orders Delivered)", type: "text" },
    ],
    lists: [
      {
        key: "images",
        label: "Screenshots",
        itemFields: [
          { key: "image", label: "Image", type: "image" },
        ],
      },
    ],
    defaultData: {
      heading: "Trusted by 1,000+ Retail Partners",
      highlightWord: "1,000+",
      statValue1: "4.9/5",
      statLabel1: "Average Rating",
      statValue2: "10K+",
      statLabel2: "Orders Delivered",
      images: [
        { image: "/WhatsApp Image 2026-06-10 at 1.15.20 PM.jpeg" },
        { image: "/WhatsApp Image 2026-06-10 at 1.15.21 PM (1).jpeg" },
        { image: "/WhatsApp Image 2026-06-10 at 1.15.21 PM (2).jpeg" },
        { image: "/WhatsApp Image 2026-06-10 at 1.15.21 PM.jpeg" },
        { image: "/WhatsApp Image 2026-06-10 at 1.15.22 PM (1).jpeg" },
        { image: "/WhatsApp Image 2026-06-10 at 1.15.22 PM.jpeg" },
      ],
    },
  },
  {
    key: "buyer_psychology",
    page: "Home",
    label: "Buyer Psychology",
    description: "\"Broad Market Appeal / Everyday Comfort / ...\" feature grid.",
    fields: [
      { key: "overline", label: "Overline", type: "text" },
      { key: "heading", label: "Heading", type: "text" },
      { key: "highlightWord", label: "Highlight Word (optional, colored)", type: "text" },
      { key: "paragraph", label: "Paragraph", type: "textarea" },
    ],
    lists: [
      {
        key: "features",
        label: "Features",
        itemFields: [
          { key: "t", label: "Title", type: "text" },
          { key: "d", label: "Description", type: "textarea" },
        ],
      },
    ],
    defaultData: {
      overline: "The Best Investment in Everyday Fashion",
      heading: "Why Smart Sellers Choose AQSHA Batik Suits",
      highlightWord: "AQSHA Batik Suits",
      paragraph: "You are investing in women's clothing collections built around repeat demand, breathable comfort, distinctive batik prints, and wearable styles customers genuinely want to buy again.",
      features: [
        { t: "Broad Market Appeal", d: "Batik suits for women and contemporary ethnic styles suited to boutiques, marketplaces, resellers, and modern fashion stores." },
        { t: "Everyday Comfort", d: "Breathable cotton dresses, cotton dress material, and comfortable kurti fabrics designed for effortless everyday wear." },
        { t: "Timeless Demand", d: "Distinctive batik print dresses and wearable styles that remain relevant across changing fashion seasons." },
        { t: "Versatile Collections", d: "Flexible collections covering batik print kurtis, suit sets for women, casual dresses for women, cotton fashion, and modern women's clothing." },
      ],
    },
  },
  {
    key: "cta_banner_marquee",
    page: "Home",
    label: "CTA Marquee Banner",
    description: "The scrolling dark banner text near the bottom of the page.",
    fields: [
      { key: "text", label: "Marquee Text", type: "text" },
    ],
    defaultData: {
      text: "Fast-Moving Suits for Women • New Batik Designs Weekly • Wholesale Orders Available",
    },
  },

  // ── ABOUT US ──
  {
    key: "about_hero",
    page: "About Us",
    label: "About Us Hero",
    description: "The heritage intro section at the top of the About Us page.",
    fields: [
      { key: "overline", label: "Overline", type: "text" },
      { key: "heading", label: "Heading", type: "textarea" },
      { key: "highlightWord", label: "Highlight Word (optional, colored)", type: "text" },
      { key: "paragraph", label: "Paragraph", type: "textarea" },
      { key: "calloutText", label: "Highlighted Callout Text", type: "textarea" },
      { key: "ctaLabel", label: "CTA Label", type: "text" },
      { key: "image", label: "Image", type: "image" },
    ],
    lists: [
      {
        key: "checklist",
        label: "Checklist Points",
        itemFields: [
          { key: "text", label: "Point", type: "text" },
        ],
      },
    ],
    defaultData: {
      overline: "OUR HERITAGE",
      heading: "Legacy Craftsmanship\nBehind Every Design",
      highlightWord: "Every Design",
      paragraph: "Rooted in Bherugarh, Ujjain, we carry forward the legacy of traditional wax batik—refined over 15+ years into premium Batik Prints Women Clothing, batik dresses, and high-quality Batik Cotton Dress for Women.",
      calloutText: "Our collections focus on durable cotton dress material and consistent wholesale fabric, built for real market demand and ready-to-sell use.",
      ctaLabel: "Get In Touch",
      image: "/About-us/about-us.png",
      checklist: [
        { text: "Traditional Batik Prints" },
        { text: "Premium Cotton Quality" },
        { text: "15+ Years Expertise" },
        { text: "Wholesale Ready" },
      ],
    },
  },
  {
    key: "about_premium_features",
    page: "About Us",
    label: "About Us — What We Stand For",
    description: "The 4-feature \"principles\" section (icons stay fixed).",
    fields: [
      { key: "tag", label: "Tag", type: "text" },
      { key: "heading", label: "Heading", type: "text" },
      { key: "highlightWord", label: "Highlight Word (optional, colored)", type: "text" },
      { key: "quote", label: "Quote", type: "textarea" },
      { key: "image", label: "Image", type: "image" },
    ],
    lists: [
      {
        key: "features",
        label: "Features (exactly 4 — each keeps its fixed icon by position)",
        itemFields: [
          { key: "t", label: "Title", type: "text" },
          { key: "d", label: "Description", type: "textarea" },
        ],
      },
    ],
    defaultData: {
      tag: "Guided by Principles",
      heading: "What We Stand For",
      highlightWord: "Stand For",
      quote: "Every piece of Batik Prints Women Clothing, cotton dress material, and Batik Cotton Dress for Women we produce is guided by principles that ensure quality, consistency, and long-term trust for buyers.",
      image: "/About-us/ujjain batik (3).webp",
      features: [
        { t: "Authentic Craftsmanship", d: "We follow traditional wax-resist techniques to create genuine batik designs, ensuring every piece reflects real craftsmanship—not mass imitation." },
        { t: "Material Integrity", d: "Our collections use high-quality cotton fabric and durable dress material, built for comfort, repeat use, and consistent wholesale demand." },
        { t: "Direct Transparency", d: "As a direct manufacturer, we offer clear pricing, reliable supply, and honest communication for long-term business partnerships." },
        { t: "Bulk Reliability", d: "We maintain ready stock and fast dispatch timelines to ensure your boutique or wholesale business never faces inventory gaps across India." },
      ],
    },
  },
  {
    key: "about_manufacturing",
    page: "About Us",
    label: "About Us — Manufacturing Standards",
    description: "The \"Our Whole Fabric Manufacturing Standards\" process section.",
    fields: [
      { key: "tag", label: "Tag", type: "text" },
      { key: "heading", label: "Heading", type: "text" },
      { key: "highlightWord", label: "Highlight Word (optional, colored)", type: "text" },
      { key: "image", label: "Image", type: "image" },
    ],
    lists: [
      {
        key: "steps",
        label: "Steps",
        itemFields: [
          { key: "t", label: "Title", type: "text" },
          { key: "d", label: "Description", type: "textarea" },
        ],
      },
    ],
    defaultData: {
      tag: "The Process",
      heading: "Our Whole Fabric Manufacturing Standards",
      highlightWord: "Manufacturing Standards",
      image: "/round-category/indian dresses for girls.webp",
      steps: [
        { t: "Premium Cotton Selection", d: "We use high-quality cotton fabric (60x60) known for comfort, durability, and suitability for daily wear and stitched garments." },
        { t: "Traditional Wax-Dyeing", d: "Our process follows original wax techniques to create detailed batik print designs with strong pattern suits clarity and lasting color." },
        { t: "Quality Control & Finishing", d: "Each batch is checked for consistency, color accuracy, and clean cutting—ensuring it is ready for bulk supply and retail use." },
      ],
    },
  },
  {
    key: "about_final_cta",
    page: "About Us",
    label: "About Us — Final CTA",
    description: "The closing \"Work Directly with the Manufacturer\" banner.",
    fields: [
      { key: "heading", label: "Heading", type: "text" },
      { key: "highlightWord", label: "Highlight Word (optional, colored)", type: "text" },
      { key: "paragraph", label: "Paragraph", type: "textarea" },
    ],
    defaultData: {
      heading: "Work Directly with the Manufacturer",
      highlightWord: "the Manufacturer",
      paragraph: "Partner with a team focused on consistent quality, reliable supply, and long-term business relationships across Indian markets.",
    },
  },

  {
    key: "about_journey",
    page: "About Us",
    label: "About Us — Our Journey",
    description: "The long-form company history with the accordion timeline. Body/phase text supports paragraphs, \"- \" bullet lists, and **bold** / *bold* emphasis — see the field hints below.",
    fields: [
      { key: "tagline", label: "Small Tagline Above Heading", type: "text" },
      { key: "heading", label: "Heading", type: "text" },
      { key: "highlightWord", label: "Highlight Word (optional, colored)", type: "text" },
      { key: "quote", label: "Intro Quote", type: "textarea" },
      { key: "bodyText", label: "Story Body (before the accordion)", type: "richtext" },
      { key: "video", label: "Video", type: "video" },
      { key: "foundationYear", label: "Foundation Year Badge — Year", type: "text" },
      { key: "foundationLabel", label: "Foundation Year Badge — Label", type: "text" },
    ],
    lists: [
      {
        key: "phases",
        label: "Timeline Phases (accordion)",
        itemFields: [
          { key: "t", label: "Phase Title", type: "text" },
          { key: "d", label: "Phase Body", type: "richtext" },
        ],
      },
    ],
    defaultData: {
      tagline: "From Handmade Batik To Trusted Women Fashion Supply",
      heading: "The Journey Behind AQSHA BATIK SUITS",
      highlightWord: "AQSHA BATIK SUITS",
      quote: "From 15 handmade suits for women in Bherugarh, Ujjain to supplying wholesalers, boutiques, and resellers across India—this journey was built on consistency, correction, and understanding what women actually want to wear.",
      video: "/videos/Video-26729.mp4",
      foundationYear: "2010",
      foundationLabel: "The Foundation Year",
      bodyText: "This didn't start as a brand.\nIt started in Bherugarh, Ujjain — where batik is not just textile work. It is craftsmanship passed through generations of hands.\n\nIn 2010, my father started with only 15 suits for women.\nSimple batik designs. Small production. No team. No big setup.\nIt took nearly 20 days to sell those first 15 pieces.\nThere was no roadmap. No certainty. Only effort.\n\nBut he did not stop.\nHe created another batch. Then another.\nSome suits sold. Some did not.\nThere were fabric mistakes. Quality issues. Losses.\nAt times, dresses had to be sold at lower prices just to recover costs and continue production.\nA small ₹10–20 thousand bank loan helped keep the work moving.\n\nBut instead of giving up, he focused on improving the foundation:\n\n- Better fabric quality\n- Better cutting and fitting\n- Better suit design for women\n- Better understanding of what buyers actually wanted\n\n**That mindset changed everything.**",
      phases: [
        {
          t: "From Local Selling To Wholesale Supply",
          d: "Instead of waiting for customers to come, he went directly to them.\nTravelled to different cities. Met wholesalers personally. Carried samples by hand.\nUnderstood what resellers were searching for in women dresses, suit sets, and designer dress collections.\n\n**That was the real turning point.**\n\nThe business slowly shifted:\nFrom retail struggle → to wholesale women fashion supply.\n\nAs demand grew, our collections expanded into:\n\n- suit set for women\n- frock suit for women\n- cotton fashion collections\n- anarkali suits for women\n- party wear suits for women\n- and breathable everyday women clothing",
        },
        {
          t: "From 15 Pieces To Thousands",
          d: "Where it once took 20 days to sell 15 pieces…\nBy 2016, AQSHA BATIK SUITS was supplying nearly 1500–2000 women clothing pieces at the same time.\n\n*That growth did not come from luck.*\n\nIt came from:\n\n- improving quality constantly\n- correcting mistakes quickly\n- understanding women dress design trends\n- and building wearable collections women repeatedly purchased\n\nEvery new design dress for women taught us something.\nEvery market visit improved our understanding of:\n\n- dress designs for women\n- fabric demand\n- fitting preferences\n- and changing fashion behavior",
        },
        {
          t: "Taking Batik Fashion Online",
          d: "In 2017, I brought AQSHA BATIK SUITS online.\n\nThrough:\n\n- WhatsApp\n- social media\n- online marketplaces\n\nour collections started reaching more wholesalers, boutiques, and women fashion buyers across India.\n\n*That digital shift changed our speed completely.*\n\nNow our collections included:\n\n- designer dresses for women\n- trendy suits for women\n- latest dress designs for womens\n- party wear dress collections\n- and breathable cotton fashion styles\n\n**The internet helped our batik craftsmanship reach beyond local markets.**",
        },
        {
          t: "The COVID Phase & Rebuilding Again",
          d: "Like many fashion businesses, COVID during 2019–2020 created losses and uncertainty.\nDemand slowed. Markets paused. Orders became unstable.\n\n*But we adapted again.*\n\nInstead of stopping, we improved systems, stock planning, and production clarity.\n\nAnd from 2022 onwards, the business returned stronger with:\n\n- better operational systems\n- stronger wholesale demand\n- improved product quality\n- and clearer fashion positioning",
        },
        {
          t: "Where AQSHA BATIK SUITS Stands Today",
          d: "Today, AQSHA BATIK SUITS supplies wholesalers, boutiques, and resellers across major Indian markets including:\n\n- Delhi\n- Punjab\n- Gujarat\n- and growing fashion markets across India\n\nWe now manufacture collections across multiple women fashion categories including:\n\n- suits for women\n- designer dress for women\n- party wear suits for women\n- frock suit for women\n- anarkali suits for women\n- night suit for women\n- cotton night suit for women\n- and stylish everyday women clothing\n\nBut even after all these years, our focus remains the same:\n\n- Creating wearable Batik Prints Women Clothinging for women that actually sells repeatedly.\n\n**Because fashion changes. Comfort, quality, and trust do not.**",
        },
      ],
    },
  },
  {
    key: "about_faq",
    page: "About Us",
    label: "About Us — FAQ",
    description: "About Us FAQ accordion. Answers support paragraphs, \"- \" bullet lists, and **bold**/*bold* emphasis (same convention as Our Journey).",
    fields: [],
    lists: [
      {
        key: "items",
        label: "Questions",
        itemFields: [
          { key: "q", label: "Question", type: "text" },
          { key: "a", label: "Answer", type: "richtext" },
        ],
      },
    ],
    defaultData: {
      items: [
        { q: "Q1. Who is AQSHA BATIK SUITS?", a: "AQSHA BATIK SUITS is a women clothing and Batik Cotton Dress for Women manufacturer based in Ujjain with 15+ years of experience in producing suits for women, batik print dress material, cotton dress collections, and wholesale women fashion products for boutiques, resellers, and wholesalers across India." },
        { q: "Q2. Where is AQSHA BATIK SUITS manufacturing located?", a: "Our manufacturing is based in Bherugarh, Ujjain (Madhya Pradesh), a region widely known for traditional batik craftsmanship, printed textile artistry, and skilled Batik Cotton Dress for Women manufacturing." },
        { q: "Q3. What makes AQSHA BATIK SUITS different from other women clothing manufacturers?", a: "We focus on:\n\n- consistent fabric quality\n- clean cutting\n- wearable women dress design\n- and fashion collections that actually perform in real wholesale markets.\n\nOur collections are built around repeat demand for:\n\n- suits for women\n- party wear suits for women\n- cotton dress material\n- and designer dresses for women." },
        { q: "Q4. Do you supply wholesale women dresses and suits for women?", a: "Yes. AQSHA BATIK SUITS primarily focuses on wholesale women dresses, suit set for women collections, batik cotton fabric, and women fashion supply for wholesalers, boutiques, resellers, and online sellers across India." },
        { q: "Q5. Which women clothing categories do you manufacture?", a: "We manufacture multiple women fashion categories including:\n\n- suits for women\n- party wear dress for women\n- frock suit for women\n- anarkali suits for women\n- cotton dresses for women\n- night suit for women\n- cotton night suit for women\n- designer dresses for women\n- and trendy women's clothing collections." },
        { q: "Q6. Which cities and markets do you currently supply to?", a: "We currently supply wholesale women clothing and batik collections across major Indian markets including Delhi, Punjab, Gujarat, and expanding fashion markets across India." },
        { q: "Q7. Do you offer ready stock for women's dresses and cotton dress material?", a: "Yes. We maintain ready stock for wholesale women dresses, cotton dress material, and batik fashion collections to support faster dispatch and bulk order requirements." },
        { q: "Q8. Can I contact AQSHA BATIK SUITS directly for wholesale women clothing inquiries?", a: "Yes. You can directly connect with AQSHA BATIK SUITS through WhatsApp or call for:\n\n- wholesale women dresses\n- suits for women business inquiries\n- cotton dress material pricing\n- reseller support\n- and bulk fashion orders." },
      ],
    },
  },

  // ── CONTACT US ──
  {
    key: "contact_hero",
    page: "Contact Us",
    label: "Contact Us Hero",
    description: "The intro section at the top of the Contact Us page.",
    fields: [
      { key: "heading", label: "Heading", type: "text" },
      { key: "highlightWord", label: "Highlight Word (optional, colored)", type: "text" },
      { key: "paragraph", label: "Paragraph", type: "textarea" },
      { key: "image", label: "Image", type: "image" },
    ],
    lists: [
      {
        key: "trustBadges",
        label: "Trust Badges (exactly 3 — each keeps its fixed icon by position)",
        itemFields: [
          { key: "label", label: "Label", type: "text" },
        ],
      },
    ],
    defaultData: {
      heading: "Let's Talk About Your Batik Cotton Dress for Women Requirements",
      highlightWord: "Requirements",
      paragraph: "Looking for premium Batik Cotton Dress for Women, Batik Prints Women Clothing, women clothing, or the latest cotton dresses for women? Whether you're a retailer, wholesaler, boutique owner, or fashion brand, our team is here to help you source high-quality collections directly from a trusted manufacturer.",
      image: "/category/contactt.png",
      trustBadges: [
        { label: "Premium Quality" },
        { label: "Bulk Orders Welcome" },
        { label: "Trusted Manufacturer" },
      ],
    },
  },
  {
    key: "contact_info",
    page: "Contact Us",
    label: "Contact Us — Info Cards",
    description: "Address, phone, and email shown in the info strip.",
    fields: [
      { key: "addressLine1", label: "Address Line 1", type: "text" },
      { key: "addressLine2", label: "Address Line 2", type: "text" },
      { key: "phone", label: "Phone", type: "text" },
      { key: "email", label: "Email", type: "text" },
    ],
    defaultData: {
      addressLine1: "Bherugarh, Ujjain,",
      addressLine2: "Madhya Pradesh 456010",
      phone: "+91 88153 73767",
      email: "Aqdaschhipa368@gmail.com",
    },
  },
  {
    key: "contact_form_section",
    page: "Contact Us",
    label: "Contact Us — Form Section",
    description: "Heading, copy, and benefits list beside the enquiry form.",
    fields: [
      { key: "overline", label: "Overline", type: "text" },
      { key: "heading", label: "Heading", type: "textarea" },
      { key: "highlightWord", label: "Highlight Word(s) (optional, colored — separate two with a | )", type: "text" },
      { key: "paragraph1", label: "Paragraph 1", type: "textarea" },
      { key: "paragraph2", label: "Paragraph 2", type: "textarea" },
      { key: "paragraph3", label: "Paragraph 3 (emphasized)", type: "textarea" },
      { key: "formCardHeading", label: "Form Card Heading", type: "text" },
      { key: "formCardHighlightWord", label: "Form Card Highlight Word", type: "text" },
    ],
    lists: [
      {
        key: "benefits",
        label: "Benefit Bullets",
        itemFields: [
          { key: "text", label: "Benefit", type: "text" },
        ],
      },
    ],
    defaultData: {
      overline: "Get In Touch",
      heading: "Get Personalized Batik\nCotton Dress for Women\nPricing & Expert Guidance",
      highlightWord: "Batik|Cotton Dress",
      paragraph1: "The right supplier doesn't just provide fabric. They help you choose collections that sell.",
      paragraph2: "At Aqsha Batik, we work closely with retailers, wholesalers, and fashion businesses looking for premium Batik Cotton Dress for Women, women clothing, and indian dresses that customers love.",
      paragraph3: "Submit your details and receive direct manufacturer pricing, catalogue access, and expert assistance.",
      formCardHeading: "Request Wholesale Access",
      formCardHighlightWord: "Wholesale Access",
      benefits: [
        { text: "Latest Batik Collection Catalog" },
        { text: "Wholesale Pricing Support" },
        { text: "Fast WhatsApp Assistance" },
        { text: "Bulk Order Guidance" },
        { text: "Ready Stock Updates" },
        { text: "Premium Quality Assurance" },
      ],
    },
  },
  {
    key: "contact_trust",
    page: "Contact Us",
    label: "Contact Us — Trust Section",
    description: "The \"Trusted By Retailers\" 4-card grid (icons stay fixed).",
    fields: [
      { key: "overline", label: "Overline", type: "text" },
      { key: "heading", label: "Heading", type: "text" },
      { key: "highlightWord", label: "Highlight Word (optional, colored)", type: "text" },
      { key: "paragraph", label: "Paragraph", type: "textarea" },
    ],
    lists: [
      {
        key: "cards",
        label: "Cards (exactly 4 — each keeps its fixed icon by position)",
        itemFields: [
          { key: "title", label: "Title", type: "text" },
          { key: "desc", label: "Description", type: "textarea" },
        ],
      },
    ],
    defaultData: {
      overline: "Why Choose Aqsha Batik",
      heading: "Trusted By Retailers & Fashion Businesses",
      highlightWord: "Fashion Businesses",
      paragraph: "For over 15 years, Aqsha Batik has helped businesses source premium-quality batik collections with confidence.",
      cards: [
        { title: "Direct Manufacturer", desc: "Buy directly from the manufacturer for better pricing, consistent quality, and reliable support." },
        { title: "Ready Stock Available", desc: "Access a wide range of ready-to-dispatch batik collections and dress materials." },
        { title: "Fast Dispatch", desc: "Quick processing and delivery to help your business maintain inventory without delays." },
        { title: "Premium Quality", desc: "Carefully crafted collections designed for retailers, wholesalers, and fashion brands." },
      ],
    },
  },
  {
    key: "contact_faq",
    page: "Contact Us",
    label: "Contact Us — FAQ",
    description: "Contact page FAQ accordion.",
    fields: [],
    lists: [
      {
        key: "items",
        label: "Questions",
        itemFields: [
          { key: "q", label: "Question", type: "text" },
          { key: "a", label: "Answer", type: "textarea" },
        ],
      },
    ],
    defaultData: {
      items: [
        { q: "Can I order Batik Cotton Dress for Women in bulk quantities?", a: "Yes. We specialize in wholesale Batik Cotton Dress for Women supply for retailers, wholesalers, boutiques, and fashion businesses across India." },
        { q: "Do you provide wholesale pricing?", a: "Yes. Contact our team or submit the enquiry form to receive the latest wholesale pricing and catalogue." },
        { q: "What is the minimum order quantity?", a: "The minimum order quantity may vary depending on the collection. Our team will guide you based on your requirements." },
        { q: "Do you ship across India?", a: "Yes. We provide reliable dispatch and delivery services across India." },
        { q: "How can I get the latest catalogue?", a: "Simply submit the enquiry form or contact us on WhatsApp to receive the latest Batik Cotton Dress for Women catalogue and pricing details." },
      ],
    },
  },
  {
    key: "contact_final_cta",
    page: "Contact Us",
    label: "Contact Us — Final CTA",
    description: "The closing banner just before the footer.",
    fields: [
      { key: "heading", label: "Heading", type: "textarea" },
      { key: "highlightWord", label: "Highlight Word (optional, colored)", type: "text" },
      { key: "paragraph", label: "Paragraph", type: "textarea" },
    ],
    defaultData: {
      heading: "Looking For Premium Batik Cotton Dress for Women At Wholesale Prices?",
      highlightWord: "Batik Cotton Dress for Women",
      paragraph: "Get direct manufacturer pricing, expert guidance, and access to our latest Batik Cotton Dress for Women, women clothing, indian dresses, and wholesale collections.",
    },
  },

  // ── SITEWIDE ──
  {
    key: "sitewide_cta_banner",
    page: "Sitewide",
    label: "Sitewide CTA Banner",
    description: "The \"Batik Suits Customers Love to Wear Again\" banner shown near the bottom of most pages (About Us, Contact Us, category pages, policy pages, blog).",
    fields: [
      { key: "tagText", label: "Tag Text", type: "text" },
      { key: "heading", label: "Heading", type: "textarea" },
      { key: "highlightWord", label: "Highlight Word (optional, colored)", type: "text" },
      { key: "paragraph", label: "Paragraph", type: "textarea" },
      { key: "image", label: "Image", type: "image" },
      { key: "ctaLabel1", label: "Primary CTA Label", type: "text" },
      { key: "ctaLabel2", label: "Secondary CTA Label", type: "text" },
    ],
    defaultData: {
      tagText: "MADE TO WEAR. MADE TO SELL.",
      heading: "Batik Suits Customers\nLove to Wear Again",
      highlightWord: "Wear Again",
      paragraph: "Discover comfortable, distinctive Batik suits made for everyday style, while giving boutiques and retailers a collection customers want to come back for.",
      image: "/luxury_ethnic_seated.png",
      ctaLabel1: "Shop Batik Suits",
      ctaLabel2: "Become a Wholesale Partner",
    },
  },

  // ── CATEGORY: ETHNIC WEAR FOR WOMEN ──
  {
    key: "ethnic_hero",
    page: "Ethnic Wear for Women",
    label: "Hero",
    description: "The top banner heading/paragraph/images and CTAs.",
    fields: [
      { key: "overline", label: "Overline", type: "text" },
      { key: "heading", label: "Heading", type: "textarea" },
      { key: "highlightWord", label: "Highlight Word (optional, colored)", type: "text" },
      { key: "paragraph", label: "Paragraph", type: "textarea" },
      { key: "imageDesktop", label: "Desktop Image", type: "image" },
      { key: "imageMobile", label: "Mobile Image", type: "image" },
      { key: "ctaLabel1", label: "Primary CTA Label", type: "text" },
      { key: "ctaLabel2", label: "Secondary CTA Label", type: "text" },
    ],
    defaultData: {
      overline: "TRADITION, REIMAGINED",
      heading: "Ethnic Wear for Women That Feels Traditional Yet Effortlessly Modern",
      highlightWord: "Yet Effortlessly Modern",
      paragraph: "Discover Batik ethnic wear for women designed to bring traditional character into everyday wardrobes. Explore breathable cotton dresses, expressive Batik kurtis, comfortable suit sets, and occasion-ready styles created for women who want culture, comfort, and individuality in every look.",
      imageDesktop: "/Hero Banner/i.png",
      imageMobile: "/Hero Banner/mobile-version/img3.png",
      ctaLabel1: "Shop Ethnic Wear",
      ctaLabel2: "Become a Wholesale Partner",
    },
  },
  {
    key: "ethnic_collection",
    page: "Ethnic Wear for Women",
    label: "Collection Section",
    description: "The 3-card highlights grid plus the two headings around it (the second heading sits right above the live product grid).",
    fields: [
      { key: "overline1", label: "Overline 1", type: "text" },
      { key: "heading1", label: "Heading 1", type: "text" },
      { key: "highlightWord1", label: "Heading 1 Highlight Word", type: "text" },
      { key: "paragraph1", label: "Paragraph 1", type: "textarea" },
      { key: "overline2", label: "Overline 2", type: "text" },
      { key: "heading2", label: "Heading 2 (above product grid)", type: "text" },
      { key: "highlightWord2", label: "Heading 2 Highlight Word", type: "text" },
      { key: "paragraph2", label: "Paragraph 2 (above product grid)", type: "textarea" },
    ],
    lists: [
      {
        key: "highlights",
        label: "Highlight Cards",
        itemFields: [
          { key: "t", label: "Title", type: "text" },
          { key: "d", label: "Description", type: "textarea" },
          { key: "img", label: "Image", type: "image" },
        ],
      },
    ],
    defaultData: {
      overline1: "Everyday Ethnic Style",
      heading1: "Indian Ethnic Wear for Women Designed for Real Life",
      highlightWord1: "Real Life",
      paragraph1: "Our Batik suits collection brings together comfortable silhouettes, handcrafted-inspired prints, and versatile styles that can move naturally from everyday routines to festive gatherings.",
      overline2: "Batik Ethnic Collection",
      heading2: "Explore Ethnic Wear for Women Made to Be Worn Beyond One Occasion",
      highlightWord2: "Beyond One Occasion",
      paragraph2: "The right ethnic outfit should feel traditional, comfortable, and easy to wear again. Explore Batik dresses, kurtis, cotton styles, and suit sets made for effortless everyday style.",
      highlights: [
        { t: "Everyday Ethnic Wear", d: "Choose comfortable Batik dresses, kurtis, and suit styles for shopping, travel, casual outings, workdays, and relaxed social occasions.", img: "/ethnic/ethnic wear for women.webp" },
        { t: "Occasion Dressing", d: "Create a more expressive look with distinctive Batik designs, elegant silhouettes, and accessories that complement your personal style.", img: "/ethnic/ethnic wear for women (1).webp" },
        { t: "Boutique & Retail", d: "Explore distinctive ethnic styles that can help boutiques and resellers build collections with stronger visual identity and everyday wearability.", img: "/ethnic/ethnic wear for women (2).webp" },
      ],
    },
  },
  {
    key: "ethnic_advantage",
    page: "Ethnic Wear for Women",
    label: "Why Choose Batik Ethnic Wear",
    description: "The tan \"why it works\" section (icons stay fixed by position).",
    fields: [
      { key: "tag", label: "Tag", type: "text" },
      { key: "heading", label: "Heading", type: "text" },
      { key: "highlightWord", label: "Highlight Word (optional, colored)", type: "text" },
      { key: "description", label: "Description", type: "textarea" },
      { key: "image", label: "Image", type: "image" },
      { key: "featureTag", label: "Overlay Tag (on image)", type: "text" },
      { key: "featureTitle", label: "Overlay Title (on image)", type: "text" },
      { key: "featureDesc", label: "Overlay Description (on image)", type: "textarea" },
    ],
    lists: [
      {
        key: "items",
        label: "Items (exactly 4)",
        itemFields: [
          { key: "title", label: "Title", type: "text" },
          { key: "desc", label: "Description", type: "textarea" },
        ],
      },
    ],
    defaultData: {
      tag: "WHY BATIK WORKS",
      heading: "Why Choose Batik Ethnic Wear for Women?",
      highlightWord: "Ethnic Wear",
      description: "The best ethnic wear balances how you look with how you feel. Batik makes that balance easier by combining expressive design with practical silhouettes and comfortable fabrics.",
      image: "/ethnic/indian ethnic wear for women.webp",
      featureTag: "FABRIC MEETS HERITAGE",
      featureTitle: "Traditional Character. Everyday Comfort.",
      featureDesc: "The right ethnic outfit should feel traditional, comfortable, and easy to wear again. Explore Batik dresses, kurtis, cotton styles, and suit sets made for effortless everyday style.",
      items: [
        { title: "Distinctive Batik Design", desc: "A thoughtfully designed Batik print can instantly give an outfit more personality without relying on excessive styling." },
        { title: "Comfortable Cotton", desc: "Cotton ethnic wear offers a breathable, practical option for women who want comfort throughout the day." },
        { title: "Versatile Silhouettes", desc: "From Batik kurtis to dresses and suit sets, versatile silhouettes make it easier to build multiple looks from one collection." },
        { title: "Made for Different Occasions", desc: "The right Batik style can work for everyday wear, summer dressing, casual gatherings, festive occasions, and selected formal settings." },
      ],
    },
  },
  {
    key: "ethnic_premium_features",
    page: "Ethnic Wear for Women",
    label: "One Wardrobe, More Ways to Wear It",
    description: "The 6-feature section with quote overlay (icons stay fixed by position).",
    fields: [
      { key: "tag", label: "Tag", type: "text" },
      { key: "heading", label: "Heading", type: "text" },
      { key: "highlightWord", label: "Highlight Word (optional, colored)", type: "text" },
      { key: "description", label: "Description", type: "textarea" },
      { key: "image", label: "Image", type: "image" },
      { key: "quoteTag", label: "Quote Overlay Tag", type: "text" },
      { key: "quoteTitle", label: "Quote Overlay Title", type: "text" },
      { key: "quoteDesc", label: "Quote Overlay Description", type: "textarea" },
    ],
    lists: [
      {
        key: "features",
        label: "Features (exactly 6)",
        itemFields: [
          { key: "t", label: "Title", type: "text" },
          { key: "d", label: "Description", type: "textarea" },
        ],
      },
    ],
    defaultData: {
      tag: "FROM DAILY TO DRESSED-UP",
      heading: "One Ethnic Wardrobe. More Ways to Wear It.",
      highlightWord: "Wear It.",
      description: "Ethnic wear does not have to mean one fixed style. The right collection gives you options.",
      image: "/ethnic/ethnic wear for women (3).webp",
      quoteTag: "STYLE WITH PURPOSE",
      quoteTitle: "From Traditional Ethnic Wear to Contemporary Women's Fashion",
      quoteDesc: "Modern ethnic dressing is about choosing pieces that work with your lifestyle.",
      features: [
        { t: "For Everyday Wear", d: "Choose lightweight Batik kurtis, relaxed dresses, and comfortable cotton styles for routines that demand ease." },
        { t: "For Work & Casual Meetings", d: "Pair a structured Batik kurti or coordinated suit set with simple accessories for a polished ethnic look." },
        { t: "For Festive Occasions", d: "Select richer Batik prints, expressive colours, and elegant silhouettes when you want your ethnic look to feel more celebratory." },
        { t: "For Weddings & Gatherings", d: "Wedding ethnic wear for women can become more memorable when traditional-inspired prints are paired with refined silhouettes and thoughtful accessories." },
        { t: "For Summer Days", d: "Choose breathable cotton ethnic styles when comfort matters as much as appearance." },
        { t: "Simple Styling Formula", d: "Batik Kurti + Straight Pants + Flats. A practical combination for everyday errands, workdays, and casual meetings." },
      ],
    },
  },
  {
    key: "ethnic_how_to_order",
    page: "Ethnic Wear for Women",
    label: "How To Order",
    description: "Heading/subtitle above the 5-step order process (steps stay fixed).",
    fields: [
      { key: "tag", label: "Tag", type: "text" },
      { key: "heading", label: "Heading", type: "text" },
      { key: "highlightWord", label: "Highlight Word (optional, colored)", type: "text" },
      { key: "subtitle", label: "Subtitle", type: "textarea" },
      { key: "ctaText", label: "CTA Label", type: "text" },
    ],
    defaultData: {
      tag: "WHOLESALE OPPORTUNITY",
      heading: "Bring Distinctive Indian Ethnic Wear for Women Into Your Collection",
      highlightWord: "Ethnic Wear",
      subtitle: "For boutiques, resellers, and retailers, Batik ethnic collections offer distinctive designs customers can wear and love again. Build a more memorable women's fashion assortment with traditional character and everyday appeal.",
      ctaText: "Start Your Wholesale Order",
    },
  },
  {
    key: "ethnic_faq",
    page: "Ethnic Wear for Women",
    label: "FAQ",
    description: "Ethnic Wear page FAQ accordion.",
    fields: [],
    lists: [
      {
        key: "items",
        label: "Questions",
        itemFields: [
          { key: "q", label: "Question", type: "text" },
          { key: "a", label: "Answer", type: "textarea" },
        ],
      },
    ],
    defaultData: {
      items: [
        { q: "What is ethnic wear for women?", a: "Ethnic wear for women includes clothing inspired by traditional regional styles, prints, silhouettes, and cultural design elements. It can include dresses, kurtis, suit sets, and other Indian-inspired women's clothing." },
        { q: "Is Batik suitable for Indian ethnic wear for women?", a: "Yes. Batik brings distinctive print character to ethnic clothing, while cotton-based styles provide practical comfort for everyday dressing." },
        { q: "What Batik ethnic wear is best for everyday use?", a: "Batik kurtis, cotton Batik dresses, lightweight suit sets, and relaxed silhouettes are practical choices for comfortable everyday ethnic dressing." },
        { q: "Where can I buy ethnic wear for women online?", a: "You can explore Batik ethnic wear collections for women's suits online from No. 1 Ujjain Batik manufacturer, Aqsha Batik Suits, and discover dresses, kurtis, suit sets, and other ethnic styles suited to your preferred design and occasion." },
        { q: "Can I buy Batik ethnic wear wholesale?", a: "Yes. Boutiques, retailers, resellers, and fashion businesses can explore available Batik collections and contact the team for product availability, quantities, pricing, and wholesale ordering." },
      ],
    },
  },

  // ── CATEGORY: NEW ARRIVALS ──
  {
    key: "newarrival_hero",
    page: "New Arrivals",
    label: "Hero",
    description: "The top banner heading/paragraph/images and CTAs.",
    fields: [
      { key: "overline", label: "Overline", type: "text" },
      { key: "heading", label: "Heading", type: "textarea" },
      { key: "highlightWord", label: "Highlight Word (optional, colored)", type: "text" },
      { key: "paragraph", label: "Paragraph", type: "textarea" },
      { key: "imageDesktop", label: "Desktop Image", type: "image" },
      { key: "imageMobile", label: "Mobile Image", type: "image" },
      { key: "ctaLabel1", label: "Primary CTA Label", type: "text" },
      { key: "ctaLabel2", label: "Secondary CTA Label", type: "text" },
    ],
    defaultData: {
      overline: "FRESH BATIK. FRESH EXPRESSION.",
      heading: "Discover New Batik Prints\nfor Women Who Want\nSomething Different",
      highlightWord: "New Batik Prints",
      paragraph: "Explore the latest Batik prints, fresh colours, expressive patterns, and comfortable cotton styles designed to bring something new to your wardrobe. From Batik print kurtis and dresses to versatile suit styles, discover designs made for everyday confidence and effortless ethnic dressing.",
      imageDesktop: "/Hero Banner/newarrival-11.png",
      imageMobile: "/Hero Banner/mobile-version/newarrival-2.png",
      ctaLabel1: "Shop New Arrivals",
      ctaLabel2: "Explore Wholesale",
    },
  },
  {
    key: "newarrival_trend_value",
    page: "New Arrivals",
    label: "Trend Value Section",
    description: "The 3-card \"why new arrivals\" section (icons stay fixed).",
    fields: [
      { key: "overline", label: "Overline", type: "text" },
      { key: "heading", label: "Heading", type: "text" },
      { key: "highlightWord", label: "Highlight Word (optional, colored)", type: "text" },
      { key: "paragraph", label: "Paragraph", type: "textarea" },
    ],
    lists: [
      {
        key: "items",
        label: "Items (exactly 3)",
        itemFields: [
          { key: "t", label: "Title", type: "text" },
          { key: "d", label: "Description", type: "textarea" },
        ],
      },
    ],
    defaultData: {
      overline: "NEW SEASON. NEW STYLE.",
      heading: "Fresh Batik Designs Made for Modern Everyday Dressing",
      highlightWord: "Everyday Dressing",
      paragraph: "Our latest Batik collection brings together distinctive Batik design, comfortable silhouettes, and versatile styles that work across everyday routines, casual outings, summer dressing, and relaxed occasions.",
      items: [
        { t: "Fresh Batik Prints", d: "Discover new patterns, expressive motifs, and contemporary colour combinations that give traditional Batik a fresh direction." },
        { t: "Everyday Cotton Styles", d: "Choose comfortable cotton dresses, kurtis, and suit styles designed for easy everyday wear." },
        { t: "Modern Ethnic Dressing", d: "Bring traditional print characters into contemporary wardrobes with versatile silhouettes that are easy to style." },
      ],
    },
  },
  {
    key: "newarrival_collection_text",
    page: "New Arrivals",
    label: "Collection Heading (above product grid)",
    description: "Heading/copy above the live product grid (products stay live).",
    fields: [
      { key: "overline", label: "Overline", type: "text" },
      { key: "heading", label: "Heading", type: "text" },
      { key: "highlightWord", label: "Highlight Word (optional, colored)", type: "text" },
      { key: "paragraph", label: "Paragraph", type: "textarea" },
    ],
    defaultData: {
      overline: "THE NEW COLLECTION",
      heading: "Explore the Latest Batik Prints, Dresses & Kurtis",
      highlightWord: "Dresses & Kurtis",
      paragraph: "Discover newly added Batik styles designed around comfort, colour, and individuality.",
    },
  },
  {
    key: "newarrival_advantage",
    page: "New Arrivals",
    label: "Why Women Choose Our Latest Prints",
    description: "The tan \"why it works\" section (icons stay fixed by position).",
    fields: [
      { key: "tag", label: "Tag", type: "text" },
      { key: "heading", label: "Heading", type: "text" },
      { key: "highlightWord", label: "Highlight Word (optional, colored)", type: "text" },
      { key: "subheading", label: "Sub-heading (smaller text under the heading)", type: "textarea" },
      { key: "image", label: "Image", type: "image" },
      { key: "featureTag", label: "Overlay Tag (on image)", type: "text" },
      { key: "featureTitle", label: "Overlay Title (on image)", type: "text" },
      { key: "featureDesc", label: "Overlay Description (on image)", type: "textarea" },
    ],
    lists: [
      {
        key: "items",
        label: "Items (exactly 4)",
        itemFields: [
          { key: "title", label: "Title", type: "text" },
          { key: "desc", label: "Description", type: "textarea" },
        ],
      },
    ],
    defaultData: {
      tag: "WHY NEW BATIK",
      heading: "Why Women Choose Our Latest Batik Prints?",
      highlightWord: "Latest Batik Prints?",
      subheading: "The newest style is not always the best style. The right new arrival is one you can actually see yourself wearing.",
      image: "/premium-cotton-kurtis-for-women-image.webp",
      featureTag: "FRESH PRINT.",
      featureTitle: "New Prints. Authentic Batik Character.",
      featureDesc: "The appeal of a new Batik print is simple. It gives familiar comfort and a fresh visual identity.",
      items: [
        { title: "Distinctive Batik Design", desc: "Fresh patterns help your wardrobe feel individual without making everyday styling complicated." },
        { title: "Comfortable Cotton", desc: "Batik cotton fabric offers a practical foundation for comfortable dresses, kurtis, and ethnic styles." },
        { title: "Versatile Styling", desc: "A Batik print kurti can work with trousers or palazzos, while a Batik dress can become an easy standalone outfit." },
        { title: "Fresh Colour Choices", desc: "New colour combinations make it easier to discover something that feels different from what you already own." },
      ],
    },
  },
  {
    key: "newarrival_premium_features",
    page: "New Arrivals",
    label: "More Ways to Wear the Latest Collection",
    description: "The 6-feature section with quote overlay (icons stay fixed by position).",
    fields: [
      { key: "tag", label: "Tag", type: "text" },
      { key: "heading", label: "Heading", type: "text" },
      { key: "highlightWord", label: "Highlight Word (optional, colored)", type: "text" },
      { key: "subheading", label: "Sub-heading (smaller text under the heading)", type: "textarea" },
      { key: "image", label: "Image", type: "image" },
      { key: "quoteTag", label: "Quote Overlay Tag", type: "text" },
      { key: "quoteTitle", label: "Quote Overlay Title", type: "text" },
      { key: "quoteDesc", label: "Quote Overlay Description", type: "textarea" },
    ],
    lists: [
      {
        key: "features",
        label: "Features (exactly 6)",
        itemFields: [
          { key: "t", label: "Title", type: "text" },
          { key: "d", label: "Description", type: "textarea" },
        ],
      },
    ],
    defaultData: {
      tag: "FROM PRINT TO OUTFIT",
      heading: "More Ways to Wear the Latest Batik Suits Collection",
      highlightWord: "Batik Suits Collection",
      subheading: "New Batik prints become more valuable when they work across your wardrobe.",
      image: "/cotton-kurti-for-women-image.webp",
      quoteTag: "STYLE WITH SOMETHING NEW",
      quoteTitle: "Fresh Prints. Easy Styling. More Reasons to Wear Batik.",
      quoteDesc: "New arrivals should not sit in your wardrobe waiting for the right occasion.",
      features: [
        { t: "For Everyday Wear", d: "Choose a Batik print kurti with straight pants and flats for a simple, polished look." },
        { t: "For Summer Days", d: "Pair a lightweight Batik dress with sandals and minimal jewellery for effortless warm-weather dressing." },
        { t: "For Casual Outings", d: "Choose printed dresses for women who want colour and personality without complicated styling." },
        { t: "For Ethnic Occasions", d: "Pair a distinctive Batik suit with elegant accessories when you want a more refined traditional look." },
        { t: "Everyday Wearability", d: "The collection focuses on styles that can move naturally from daily routines to casual gatherings and seasonal dressing." },
        { t: "Versatile Women's Clothing", d: "Discover breathable Batik styles, cotton dresses, and printed women's clothing designed for everyday comfort, effortless styling, and seasonal wear." },
      ],
    },
  },
  {
    key: "newarrival_how_to_order",
    page: "New Arrivals",
    label: "How To Order",
    description: "Heading/subtitle above the 5-step order process (steps stay fixed).",
    fields: [
      { key: "tag", label: "Tag", type: "text" },
      { key: "heading", label: "Heading", type: "text" },
      { key: "highlightWord", label: "Highlight Word (optional, colored)", type: "text" },
      { key: "subtitle", label: "Subtitle", type: "textarea" },
    ],
    defaultData: {
      tag: "FOR WOMEN & BUSINESSES",
      heading: "New Batik Prints That Create Fresh Opportunities",
      highlightWord: "Fresh Opportunities",
      subtitle: "For women, new Batik arrivals bring fresh ways to express personal style. For boutiques and retailers, they offer distinctive designs to refresh collections with styles customers want to wear again.",
    },
  },
  {
    key: "newarrival_faq",
    page: "New Arrivals",
    label: "FAQ",
    description: "New Arrivals page FAQ accordion.",
    fields: [],
    lists: [
      {
        key: "items",
        label: "Questions",
        itemFields: [
          { key: "q", label: "Question", type: "text" },
          { key: "a", label: "Answer", type: "textarea" },
        ],
      },
    ],
    defaultData: {
      items: [
        { q: "What are the latest Batik print designs?", a: "The latest Batik print designs include fresh patterns, colours, motifs, and contemporary interpretations of traditional Batik. New arrivals may include kurtis, dresses, suits, and other cotton styles." },
        { q: "What is a Batik print kurti?", a: "A Batik print kurti combines traditional Batik patterns with a versatile kurti silhouette. It can be styled with trousers, palazzos, leggings, or other everyday bottoms." },
        { q: "Are Batik cotton dresses suitable for summer?", a: "Yes. Lightweight Batik cotton dresses can be a practical choice for warmer weather because cotton offers a breathable and comfortable feel." },
        { q: "Can I buy Batik print dress material?", a: "Yes. Batik print dress material and Batik cotton fabric can give customers, designers, boutiques, and retailers greater flexibility to create their preferred styles." },
        { q: "Can I buy new Batik prints wholesale?", a: "Yes. Boutiques, retailers, resellers, and fashion businesses can explore new Batik collections and contact the team for available designs, quantities, pricing, and wholesale ordering." },
      ],
    },
  },
];
